// Theme catalog — lists and status-bar colors derived from DaisyUI's own
// theme definitions (color-scheme decides light/dark; light themes use the
// primary hex, dark themes base-100, so white status-bar text stays legible).
// Auto-generated by scripts/generate-meta-colors.mjs — do not edit manually.
// The inline pre-paint bootstrap in partials/head-common.html carries its own
// generated copy (it cannot import modules); the generator writes both.

export const DEFAULT_LIGHT_THEME = 'caramellatte';
export const DEFAULT_DARK_THEME = 'coffee';

export const LIGHT_THEMES = [
  'retro', 'bumblebee', 'fantasy', 'lofi', 'garden', 'pastel', 'cupcake', 'emerald',
  'light', 'silk', 'nord', 'cyberpunk', 'acid', 'caramellatte', 'corporate', 'autumn',
  'wireframe', 'valentine', 'cmyk', 'winter', 'lemonade'
];

export const DARK_THEMES = [
  'aqua', 'coffee', 'halloween', 'night', 'dark', 'synthwave', 'dim', 'business',
  'sunset', 'forest', 'dracula', 'abyss', 'luxury', 'black'
];

export const META_COLORS = {
  retro:        '#ff9fa0',
  bumblebee:    '#fdc700',
  fantasy:      '#6d0076',
  lofi:         '#0d0d0d',
  garden:       '#fe0075',
  pastel:       '#e9d4ff',
  cupcake:      '#44ebd3',
  emerald:      '#66cc8a',
  light:        '#422ad5',
  silk:         '#1c1c29',
  nord:         '#5e81ac',
  cyberpunk:    '#ff6596',
  acid:         '#ff00ff',
  caramellatte: '#000000',
  corporate:    '#0082ce',
  autumn:       '#8c0327',
  wireframe:    '#d4d4d4',
  valentine:    '#f43098',
  cmyk:         '#45aeee',
  winter:       '#0069ff',
  lemonade:     '#419400',
  aqua:         '#1a368b',
  coffee:       '#261b25',
  halloween:    '#1b1816',
  night:        '#0f172a',
  dark:         '#1d232a',
  synthwave:    '#09002f',
  dim:          '#2a303c',
  business:     '#202020',
  sunset:       '#121c22',
  forest:       '#1b1717',
  dracula:      '#282a36',
  abyss:        '#001e29',
  luxury:       '#09090b',
  black:        '#000000'
};
